services:
  postgres-server:
    networks:
      - default
    build:
      context: ./
      dockerfile: Dockerfile-postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "test", "-U", "admin" ]
      interval: 10s
      timeout: 60s
      retries: 3
      start_period: 10s

  application-jar:
    networks:
      - default
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      postgres-server:
        condition: service_healthy
    ports:
      - "8082:8082"
networks:
  default:
    driver: bridge
